# -----------------------------------------------------------------------------
# SnowballRun: Simple OpenGL game
# TRAVIS CI file. (This project is tested on LINUX platform)
# Distributed under the GPL-3.0 License.
# See file `LICENSE` for more details.
#------------------------------------------------------------------------------
language: cpp
sudo: required
dist: focal
branches:
    only:
        - master
compiler:
    - g++
os:
    # Only test CI in linux
    - linux
before_install:
    # Notice that the GLFW requires a working X11 display and makefont uses GLFW.
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
install:
    # Update system here
    - sudo apt-get update -qq
    # Install dependencies libraries (cmake, g++ compiler, glew, X11 and boost libraries)
    # Notice that BOOST library is needed for ASSIMP
    - sudo apt-get install build-essential libglew-dev libxmu-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libboost-all-dev
    # Prepare manual installation of dependencies
    # Download and build other required dependencies here (just temporary)
    - mkdir travis_tmp/ && cd travis_tmp
    # GLFW 3.2.1 install
    # Download source files from GitHub and compile them by CMake
    - wget -O glfw-3.2.1.zip https://github.com/glfw/glfw/archive/3.2.1.zip
    - unzip glfw-3.2.1.zip
    - cd glfw-3.2.1
    - mkdir build && cd build
    - cmake -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLIB_SUFFIX=/x86_64-linux-gnu ..
    - make && sudo make install
    - cd ../..
    # GLM 0.9.8.4 install
    # Download source files from GitHub
    # Notice that merely include the GLM headers is allowed
    - wget -O glm-0.9.8.4.zip https://github.com/g-truc/glm/releases/download/0.9.8.4/glm-0.9.8.4.zip
    - unzip glm-0.9.8.4.zip
    - cd glm
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DGLM_INSTALL_ENABLE=ON ..
    - make && sudo make install
    - cd ../..
    # SDL2 (Version 2.0.5) install
    # Download source files from official site
    - wget -O SDL2-2.0.5.zip https://www.libsdl.org/release/SDL2-2.0.5.zip
    - unzip SDL2-2.0.5.zip
    - cd SDL2-2.0.5
    - ./configure
    - make && sudo make install
    - cd ..
    # SDL2_image (Version 2.0.1) install
    # Download source files from official site
    - wget -O SDL2_image-2.0.1.zip https://www.libsdl.org/projects/SDL_image/release/SDL2_image-2.0.1.zip
    - unzip SDL2_image-2.0.1.zip
    - cd SDL2_image-2.0.1
    - ./configure
    - make && sudo make install
    - cd ..
    # ASSIMP (Version 3.3.1) install
    # Download source file from GitHub
    - wget -O assimp-3.3.1.zip https://codeload.github.com/assimp/assimp/zip/v3.3.1
    - unzip assimp-3.3.1.zip
    - cd assimp-3.3.1
    - mkdir build
    - cd build
    - cmake ..
    - make && sudo make install
    - cd ../../..
addons:
    apt:
        sources:
            - kubuntu-backports
        packages:
            - cmake
script:
    - mkdir build
    - cd build
    - cmake ..
    - make
notifications:
    email:
        recipients:
            - enzoliao95@gmail.com
    on_success: never
    on_failure: always
