language: cpp
dist: focal
branches:
    only:
        - master
compiler:
    - g++
os:
    - linux
install:
    - sudo apt-get update -qq
    - sudo apt-get install build-essential libglew-dev libxmu-dev libxi-dev libxrandr-dev libxinerama-dev libxcursor-dev libboost-all-dev cmake assimp-utils libassimp-dev libsdl2-dev libsdl2-image-dev libglfw3-dev
    - mkdir tmp && cd tmp
    - wget -O glm-0.9.8.4.zip https://github.com/g-truc/glm/releases/download/0.9.8.4/glm-0.9.8.4.zip
    - unzip glm-0.9.8.4.zip
    - cd glm
    - mkdir build && cd build
    - cmake -DCMAKE_INSTALL_PREFIX=/usr/local -DGLM_INSTALL_ENABLE=ON ..
    - make && sudo make install
    - cd ../../..
script:
    - mkdir build
    - cd build
    - cmake ..
    - make -j$(nproc)
notifications:
    email:
        recipients:
            - enzoliao95@gmail.com
    on_success: never
    on_failure: always
